DROP TABLE remitTbl;
DROP TABLE remitFavTbl;
DROP TABLE accountTbl;
DROP TABLE bankTbl;
DROP TABLE userTbl;

DROP SEQUENCE NOSEQ;

-- 회원 테이블 : userTbl
CREATE TABLE userTbl (
    id varchar2(8) primary key,
    password varchar2(12) not null,
    uname nvarchar2(4) not null,
    birth date not null,
    tel varchar2(11)
);

-- 은행 테이블 : bankTbl
CREATE TABLE bankTbl (
    bcode char(2) primary key,
    bname nvarchar2(9) not null
);

-- 계좌 테이블 : accountTbl
CREATE TABLE accountTbl (
    aid varchar2(16) primary key,
    id varchar2(8),
    bcode char(2),
    balance number(10) default 0
);

ALTER TABLE ACCOUNTTBL
ADD CONSTRAINT ACCOUNTTBL_FK1 FOREIGN KEY
(
  ID 
)
REFERENCES USERTBL
(
  ID 
)
ENABLE;

ALTER TABLE ACCOUNTTBL
ADD CONSTRAINT ACCOUNTTBL_FK2 FOREIGN KEY
(
  BCODE 
)
REFERENCES BANKTBL
(
  BCODE 
)
ENABLE;

CREATE SEQUENCE NOSEQ INCREMENT BY 1 START WITH 1;

-- 송금 로그 테이블 : remitTbl
CREATE TABLE remitTbl (
    no number(11) primary key,
    outaid varchar2(16),
    inaid varchar2(16),
    price number(6) not null
);

CREATE TRIGGER REMITTBL_TRG 
BEFORE INSERT ON REMITTBL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.NO IS NULL THEN
      SELECT NOSEQ.NEXTVAL INTO :NEW.NO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/

ALTER TABLE REMITTBL
ADD CONSTRAINT REMITTBL_FK1 FOREIGN KEY
(
  OUTAID 
)
REFERENCES ACCOUNTTBL
(
  AID 
)
ENABLE;

ALTER TABLE REMITTBL
ADD CONSTRAINT REMITTBL_FK2 FOREIGN KEY
(
  INAID 
)
REFERENCES ACCOUNTTBL
(
  AID 
)
ENABLE;

-- 자주 송금한 계좌 테이블 : remitFavTbl
CREATE TABLE remitFavTbl (
    outaid varchar2(16),
    inaid varchar2(16),
    count number(11) default 0
);

ALTER TABLE REMITFAVTBL
ADD CONSTRAINT REMITFAVTBL_FK1 FOREIGN KEY
(
  OUTAID 
)
REFERENCES ACCOUNTTBL
(
  AID 
)
ENABLE;

ALTER TABLE REMITFAVTBL
ADD CONSTRAINT REMITFAVTBL_FK2 FOREIGN KEY
(
  INAID 
)
REFERENCES ACCOUNTTBL
(
  AID 
)
ENABLE;


-- 더미 데이터 INSERT
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('01', N'KB국민은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('02', N'KDB산업은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('03', N'NH농협은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('04', N'신한은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('05', N'우리은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('06', N'스탠다드차타드은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('07', N'KEB하나은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('08', N'IBK기업은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('09', N'한국씨티은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('10', N'SH수협은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('11', N'DGB대구은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('12', N'BNK부산은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('13', N'광주은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('14', N'제주은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('15', N'전북은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('16', N'BNK경남은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('17', N'케이뱅크은행');
INSERT INTO BANKTBL (BCODE, BNAME) VALUES ('18', N'한국카카오은행');

--SELECT TEST
SELECT * FROM accountTbl WHERE id = 'ddd';
